config/routes.rb
Rails.application.routes.draw do
  resources :trivia_squads, only: [:show,:new, :create, :destroy]
  resources :players
  resources :teams
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
    has_many :trivia_squads
    has_many :teams, through: :trivia_squads
    validates :name, :nickname, :expertise, :catchphrase, presence: true
    validates :nickname, :catchphrase, uniqueness: true
    validates :catchphrase, length: {minimum: 2, maximum: 200}
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :trivia_squads
    has_many :players, through: :trivia_squads
    validates :name, :max_member_count, :slogan, :winning_note, :losing_note, presence: true
    validates :name, :slogan, :winning_note, :losing_note, uniqueness: true
    validates :slogan, length: {minimum: 2, maximum: 200}
    validates :winning_note, :losing_note, length: {minimum: 2, maximum: 200}
    validates :max_member_count, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 6}
    validates :recruiting, inclusion: { in: [true, false] }
    validates :recruiting, exclusion: { in: [nil] }

    def self.recruiting_teams
        recruiting_teams = Team.all.select { |team| team.recruiting && team.players.count < team.max_member_count}
        #byebug
        recruiting_teams
    end
    
end

app/models/trivia_squad.rb
class TriviaSquad < ApplicationRecord
    belongs_to :team
    belongs_to :player
    validates :team_id, :player_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    before_action :find_player, only: [:show, :edit, :update, :destroy]

    def index
        @players = Player.all
    end

    def show
    end

    def new
        @player = Player.new
    end

    def create
        @player = Player.create(player_params)
        if @player.valid?
            redirect_to player_path(@player)
        else
            flash[:errors] = @player.errors.full_messages
            redirect_to new_player_path
        end
    end

    def edit
    end

    def update
        if @player.update(player_params)
            redirect_to player_path(@player)
        else
            flash[:errors] = player.errors.full_messages
            redirect_to edit_player_path
        end
    end

    def destroy
        @player.destroy
        redirect_to players_path
    end

    private

    def find_player
        @player = Player.find(params[:id])
    end

    def player_params
        params.require(:player).permit(:name, :nickname, :expertise, :catchphrase)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
    before_action :find_team, only: [:show, :edit, :update, :destroy]

    def index
        @teams = Team.all
    end

    def show
    end

    def new
        @team = Team.new
    end

    def create
        @team = Team.create(team_params)
        if @team.valid?
            redirect_to team_path(@team)
        else
            flash[:errors] = @team.errors.full_messages
            redirect_to new_team_path
        end
    end

    def edit
    end

    def update
        if @team.update(team_params)
            redirect_to team_path(@team)
        else
            flash[:errors] = @team.errors.full_messages
            redirect_to edit_team_path
        end
    end

    def destroy
        @team.destroy
    end

    private

    def find_team
        @team = Team.find(params[:id])
    end

    def team_params
        params.require(:team).permit(:name, :max_member_count, :slogan, :winning_note, :losing_note, :trivia_nights_won, :recruiting)
    end
end

app/controllers/trivia_squads_controller.rb
class TriviaSquadsController < ApplicationController

    def new
        @trivia_squad = TriviaSquad.new
        @recruiting_teams = Team.recruiting_teams
    end

    def create
        @trivia_squad = TriviaSquad.find_or_create_by(squad_params)
        if @trivia_squad.valid?
            redirect_to team_path(@trivia_squad.team)
        else
            flash[:errors] = @trivia_squad.errors.full_messages
            redirect_to new_trivia_squad_path
        end
    end

    def destroy
        @trivia_squad = TriviaSquad.find(params[:id])
        team = @trivia_squad.team
        @trivia_squad.destroy
        redirect_to team_path(team)
    end

    private

    def squad_params
        params.require(:trivia_squad).permit(:team_id, :player_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/trivia_squads_helper.rb
module TriviaSquadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LegendaryOctoPalmTree</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_player.form.html.erb
<% if flash[:errors] %>
<ul>
    <% flash[:errors].map do |error| %>
        <li><%= error %></li>
    <% end %>
</ul>
<% end %>

<%= form_for @player do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %><br>
    <%= f.label :expertise %><br>
    <%= f.text_field :expertise %><br>
    <%= f.label :catchphrase %><br>
    <%= f.text_area :catchphrase %><br><br>
    <%= f.submit %>
<% end%>

app/views/players/edit.html.erb
<h1>Trivia Squad Pro</h1>
<p>
    <%= link_to "All Trivia Squads", teams_path %> | 
    <%= link_to "All Players", players_path %> | 
    <%= link_to "Create Trivia Squad", new_team_path %> |
    <%= link_to "Join a Trivia Squad", new_trivia_squad_path %> |
    <%= link_to "Register New Player", new_player_path %>
</p>
<h2>Update Player Account</h2>
<%= render "player.form" %>

app/views/players/index.html.erb
<h1>Trivia Squad Pro</h1>
<p>
    <%= link_to "All Trivia Squads", teams_path %> | 
    <%= link_to "All Players", players_path %> | 
    <%= link_to "Create Trivia Squad", new_team_path %> |
    <%= link_to "Join a Trivia Squad", new_trivia_squad_path %> |
    <%= link_to "Register New Player", new_player_path %>
</p>
<h2>All Players</h2>

<ul>
    <% @players.each do |player| %>
    <li><%= link_to player.name, player_path(player) %></li>
    <% end %>
</ul>

app/views/players/new.html.erb
<h1>Trivia Squad Pro</h1>
<p>
    <%= link_to "All Trivia Squads", teams_path %> | 
    <%= link_to "All Players", players_path %> | 
    <%= link_to "Create Trivia Squad", new_team_path %> |
    <%= link_to "Join a Trivia Squad", new_trivia_squad_path %> |
    <%= link_to "Register New Player", new_player_path %>
</p>
<h2>Register Player Account</h2>
<%= render "player.form" %>

app/views/players/show.html.erb
<h1>Trivia Squad Pro</h1>
<p>
    <%= link_to "All Trivia Squads", teams_path %> | 
    <%= link_to "All Players", players_path %> | 
    <%= link_to "Create Trivia Squad", new_team_path %> |
    <%= link_to "Join a Trivia Squad", new_trivia_squad_path %> |
    <%= link_to "Register New Player", new_player_path %>
</p>
<h2><%= @player.name %>'s Profile</h2>
<p>Nickname: <em><%= @player.nickname %></em></p>
<p>Expertise: <%= @player.expertise %></p>
<p>Catchphrase: <br><br><%= @player.catchphrase %></p>
<p>Squads Joined: 
<ul>    
    <% @player.teams.each do |team| %>
    <li><%= link_to team.name, team_path(team) %></li>
    <% end%>
</ul>
</p>

app/views/trivia_squads/_join.squad.html.erb
<% if flash[:errors] %>
<ul>
    <% flash[:errors].map do |error| %>
        <li><%= error %></li>
    <% end %>
</ul>
<% end %>

<%= form_for @trivia_squad do |f| %>
    <%= f.label :team_id, "Team Name" %><br>
    <%= f.collection_select :team_id, @recruiting_teams, :id, :name %><br>
    <%= f.label :player_id, "Player Name" %><br>
    <%= f.collection_select :player_id, Player.all, :id, :name %><br><br>
    <%= f.submit "Join Trivia Squad"%>
<% end%>

app/views/trivia_squads/new.html.erb
<h1>Trivia Squad Pro</h1>
<p>
    <%= link_to "All Trivia Squads", teams_path %> | 
    <%= link_to "All Players", players_path %> | 
    <%= link_to "Create Trivia Squad", new_team_path %> |
    <%= link_to "Join a Trivia Squad", new_trivia_squad_path %> |
    <%= link_to "Register New Player", new_player_path %>
</p>
<h2>Join A Trivia Squad</h2>
<%= render "join.squad" %>